version: '3'
services:
  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile-dev
    container_name: video-streaming
    volumes:
      - /tmp/video-streaming-node/npm-cache:/root/.npm:z
      - ./video-streaming/src:/usr/src/app/src:z
    ports:
      - "4000:80"
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
      - DBHOST=mongodb://mongo-db:27017
      - DBNAME=video-streaming
      - NODE_ENV=development
    restart: "no"
  video-storage:
    image: video-storage
    build:
      context: ./video-storage
      dockerfile: Dockerfile-dev
    container_name: video-storage
    volumes:
      - /tmp/video-streaming-node/npm-cache:/root/.npm:z
      - ./video-storage/src:/usr/src/app/src:z
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT_NAME}
      - STORAGE_ACCESS_KEY=${STORAGE_ACCESS_KEY}
      - NODE_ENV=development
    restart: "no"

  history:
    image: history
    build:
      context: ./history
      dockerfile: Dockerfile-dev
    container_name: history

    volumes:
      - /tmp/video-streaming-node/npm-cache:/root/.npm:z
      - ./history/src:/usr/src/app/src:z
    ports:
      - "4003:80"
    environment:
      - PORT=80
      - DBHOST=mongodb://mongo-db:27017
      - DBNAME=history
      - NODE_ENV=development
    restart: "no"


  mongo-db:
    image: mongo:5.0.6
    container_name: mongo-db
    ports:
      - "4002:27017"
    restart: "always"
  mongo-seed:
    build:
      context: ./mongo-seed
      dockerfile: Dockerfile
    depends_on:
      - mongo-db