version: '3'
services:

  video-streaming:
    image: video-streaming-node
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming-node
    ports:
      - "4000:80"
    environment:
      - PORT=80
    restart: "no"